name: ci

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          fail

